name: E2E
on: [deployment_status]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: End-to-End tests (Cypress)
        uses: cypress-io/github-action@v5
        with:
          record: true
          parallel: true
          command: npm run e2e:ci baseUrl=${{ github.event.deployment_status.deployment_url }}
        if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
